database: MessageNatterUsers
username: MessageNatterUsersService
password: MessageNatterUsersService
options:
  dialect: mysql
  host: users-db
  port: 3306
  pool:
    max: 20,
    min: 0,
    idle: 10000
  dialectOptions:
    charset: 'utf8mb4'
  logging: false